### ISSUE TITLE
The reward delta of Mangata auto-compound is not displayed correct.

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/xcm-demo#33]
This happens in mangata-rococo.

Before
Claimable reward in MGR-TUR: 1
Before auto-compound, 1st Account reserved "MGR-TUR": 184 ...

After （应该是reserved MGR-TUR这里错了，新的值应该是截图里的，u128: 15,121,576,034,313)
After auto-compound, reserved MGR-TUR is: 0 planck ...
1st Account has compounded -184221048304413054685 planck more MGR-TUR ...

Actual Execution
![CleanShot 2023-02-08 at 10 08 57](https://user-images.githubusercontent.com/2616844/217688712-a90d1875-60b0-4245-b643-b0d83b425f4b.png)

**Comment by imstar15** [comment]
PR https://github.com/OAK-Foundation/xcm-demo/pull/34
