### ISSUE TITLE
Add balance check and skip this transfer if balance is not lower than topUpAmount

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/xcm-demo#49]
@imstar15

_Originally posted by @chrisli30 in https://github.com/OAK-Foundation/xcm-demo/pull/46#discussion_r1174661029_

**Comment by chrisli30** [comment]
Double check this issue in moonbase-local and resolve this if it’s already fixed.

**Comment by imstar15** [comment]
Yes, I have checked it.

https://github.com/OAK-Foundation/xcm-demo/blob/c4464067c59cf324ac0af63fbdab26179a34a46d/src/moonbeam/common.js#L73

https://github.com/OAK-Foundation/xcm-demo/blob/c4464067c59cf324ac0af63fbdab26179a34a46d/src/moonbeam/common.js#L106
